### ISSUE TITLE
Advantages of TyphoonFactoryProvider over runtime args? 

### ISSUE THREAD

**Issue by jasperblues** [appsquickly/Typhoon#225]
What are the advantages of TyphoonFactoryProvider over runtime args? (if any). 

We were able to get runtime args in sooner than expected. Would it make sense to deprecate TyphoonFactoryProvider in favor of runtime args?

**Comment by PabloLerma** [comment]
Hi @jasperblues !

I'm looking for a migration guide between version because we were in 1.8.2 and want to updated (to 3.4.5).
Basically we were using tons of [TyphoonFactoryProvider withProtocol:dependencies:factory] and some [TyphoonFactoryProvider withProtocol:dependencies:factories].
Please could you tell me how could I migrate the following example code:

    - (id)loginWebViewControllerProvider {
	return [TyphoonFactoryProvider withProtocol:@protocol(EXLoginWebViewControllerProvider) dependencies:^(TyphoonDefinition *definition) {
		[definition injectProperty:@selector(webViewFacade)];
		
		definition.scope = TyphoonScopeSingleton;
	} factory:^(id<EXLoginWebViewControllerProvider> provider, NSURL *url) {
		return [[EXLoginWebViewController alloc] initWithWebViewFacade:provider.webViewFacade
																   url:url];
	}];
    }

I am lost :(

**Comment by jasperblues** [comment]
Was it not clear after reading about: https://github.com/appsquickly/Typhoon/wiki/Types-of-Injections#injection-with-run-time-arguments

If not could you provide some more code? The code for your factory provider, etc?
