### ISSUE TITLE
For initializer method not found error, add instructions for user on Swift protocols (they require @objc directive to be dynamic)

### ISSUE THREAD

**Issue by jasperblues** [appsquickly/Typhoon#257]

**Comment by fatuhoku** [comment]
Hi @jasperblues, how's it going.

I just opened up #417 because I ran into the 'initializer not found' problem because I wanted my initializer to take two Swift protocols as parameters.

The error was not very clear, that's for sure: and the solution less clearer still. What if I really do want to use Typhoon to declare a Swift component that gets initialized with something that conforms to a Swift protocol?  What if I don't want to be forced to have to name my initializer, nor make my protocols be `@objc`?

Is this officially a limitation of Typhoon? Because right now the only solution I can see is to initialize that component by hand!

**Comment by fatuhoku** [comment]
Plus, if there was a note written about this, I definitely don't see it!
