### ISSUE TITLE
Run-time Arguments Supported with Swift Assembly?

### ISSUE THREAD

**Issue by ghost** [appsquickly/Typhoon#293]
Hi,

I'm attempting to update my project to use Swift for all my TyphoonAssembly code. I've had some success, but I'm stuck trying to pass run-time arguments to a controller. Here's my code:

```
dynamic func webControllerForPath(path: String) -> AnyObject {
    return TyphoonDefinition.withClass(WebViewController.self) { (definition) in
        definition.parent = self.baseController();
        definition.useInitializer("initWithNibName:bundle:") { (initializer) in
            initializer.injectParameterWith("WebViewController");
            initializer.injectParameterWith(NSBundle.mainBundle());
        }
        definition.injectProperty("path", with: path);
    }
}
```

That last line is causing a crash. Specifically:

```
*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: 'You can't call a method on the runtime argument being passed in. It has to be passed in as-is'
```

Is this not supported? Thanks.

**Comment by tspecht** [comment]
Hey! Sorry for posting on this issue, but I'm currently running into the same issue with the following code:

```
dynamic func typhoonStoryboard(name: NSString) -> AnyObject {
        return TyphoonDefinition.withClass(TyphoonStoryboard.self, configuration: { (definition) -> Void in
            definition.useInitializer("storyboardWithName:factory:bundle:", parameters: { (initializer) -> Void in
                initializer.injectParameterWith(name)
                initializer.injectParameterWith(self)
                initializer.injectParameterWith(NSBundle.mainBundle())
            })
        })
    }
    
    func viewController(withStoryboardName storyboardName: NSString, storyboardIdentifier: NSString) -> AnyObject {
        return TyphoonDefinition.withFactory(self.typhoonStoryboard(NSString(string: storyboardName)), selector: "instantiateViewControllerWithIdentifier:", parameters: { (method) -> Void in
            method.injectParameterWith(NSString(string: storyboardIdentifier))
        }, configuration: { (definition) -> Void in
            
        })
    }
```

 Any idea what could be wrong? Like you see I'm already doing the workaround with NSString but it still crashes with above exception...

**Comment by jasperblues** [comment]
Hello @tspecht it is probably better to post on StackOverflow but in either case please include the crash/console output.

**Comment by tspecht** [comment]
@jasperblues thanks for the quick response! I added the crashlog and will also post on Stackoverflow, thought asking here directly would be more direct ;)

**Comment by alexgarbarev** [comment]
@tspecht `You can't call a method on the runtime argument being passed in. It has to be passed in as-is`
while you passing runtime argument into `NSString(string: storyboardName))`

**Comment by jasperblues** [comment]
@tspecht So that means: 

* The parameter is already specified as NSString, so just pass in as-is. No need to wrap with: 

```
NSString(string: storyboardName)
```

If you interested in the behind-the-scenes info on the reason for this it is because:

* Typhoon gather information from all the assemblies on how to build objects at startup. 
* At runtime the assembly interface poses in front of the TyphoonComponentFactory which knows how to emit components based on all of those gathered rules. 

Therefore: At startup we are just capturing information about which parameter is routed where. Typhoon is a typical introspective/reflective style of DI container -> Rules/blue-prints first->post-processors->instantiation of components. 

You're welcome to ask here on GH, just that on StackOverflow you might get a larger audience and its indexed well by Google too.
