### ISSUE TITLE
-injectMethod:parameters: should be renamed

### ISSUE THREAD

**Issue by fatuhoku** [appsquickly/Typhoon#309]
The method `-injectMethod:parameters:` is confusing.  It sounds like this method injects methods into the definition, when in fact it's **declaring** that a method should be _used for_ injection, and that the given parameters should be used to feed the nominated method.

Debate!

**Comment by jasperblues** [comment]
Did you have a suggestion? with the number of folks using Typhoon 2.0, it would have some impact. Also, although method injection isn't a great name it's the one used by DI containers in other  language - it helps to have consistency here.

**Comment by alexgarbarev** [comment]
I think original name was *injectWithMethod:* then selector goes, that identifies method.
But then method name goes to be shorter - and has two part:
1) inject <- prefix of all other *inejct* method names
2) method <- type of injection
can be read as inject (dot) ... Method, params or inject (dot, pause) Property, params

Why only `injectMethod` looks confusing for you? Because `injectProperty` have same naming..
We can revert names to old one like `injectWithMethod` and `injectWithProperty`

**Comment by alexgarbarev** [comment]
I think there is dicussion about "short names" vs "understandable names"
short names has befenit - faster to type (that was very important when DI used without autowiring - too much typing)
understandable names good at start time, but after you understand the meaning not so much benefit

Another method name can looks strange:
`TyphoonDefinition withClass:` since in objective-c it's not common to name constructor starting `with`, it's common to name like `definitionWithClass:` or use `initWithClass`.. but it's very usefull to type - avoid typing obvious things.
I think this is same discussion..

In my opinion - I prefer shorter method names, since they used often

**Comment by jasperblues** [comment]
I also prefer the shorter names. And repeat the point above: Unless we come up with a name that is out-of-this-world better, I prefer to keep the API stable for existing users.

**Comment by jasperblues** [comment]
Thanks for the suggestion, but in the interests of stability, let's stick with the original name.
