### ISSUE TITLE
Loading object from assembly crashes only in release mode

### ISSUE THREAD

**Issue by sahara108** [appsquickly/Typhoon#310]
I want to test the `TyphoonScope`, so that in your swift example `PocketForecast`, I add this method in `ApplicationAssembly`:
`public dynamic func customObj() -> AnyObject {
        return TyphoonDefinition.withClass(Temperature.self) {
            (definition) in
            definition.scope = .LazySingleton
            definition.useInitializer("initWithCelciusString:") {
                (initializer) in
                initializer.injectParameterWith("1000")
            }
        }
    }`
Now what I want is when I perform an action I will call my `customObj` and check its address.
So, in `RootViewController`'s `showCitiesListController`, I call `let tempObj = self.assembly.customObj()`. (I should create a button to do that, but forgive me, I just want a quick test).
This code runs well in debug mode but not in release mode and throws exception `[NSUserDefaults copyWithZone:]: unrecognized selector sent to instance 0x7fab98e106f0`. 
Also I really want to know why it crashes inside `NSUserDefaults` while I don't make any call to `NSUserDefaults` class. 
Thanks.

**Comment by jasperblues** [comment]
Unfortunately Swift can perform some optimizations of UIKit or NSFoundation classes resulting in methods being inlined or invoked in a static fashion, even if the method is overridden and marked 'dynamic'.  It prevents runtime method invocation that is required by Typhoon. 

The workaround is to provide a custom initializer instead of using one of the Foundation ones. Eg MyViewController.initWithNibName:bundle can cause the same problem, but using a custom initializer won't. Although possible to workaround, this is quite a limitation and we want to make this more clear in the Typhoon docs. 

Meantime, we'll need to see some more code to help. 

Related #286  . . we've raised a Radar bug about this.

**Comment by sahara108** [comment]
If I use `return TyphoonDefinition.withClass(Temperature.self) {
            (definition) in
            definition.useInitializer("init")
        }`
and overwrite the `init` method, it works well in both `debug` and `release`

**Comment by jasperblues** [comment]
Oops. Didn't see you were using "one of your own" classes. Did your try marking `initWithCelciusString` as dynamic?

**Comment by jasperblues** [comment]
ie, you can just mark the method as dynamic, like this: 

```swift
    public dynamic convenience init(celciusString : String) {
        let fahrenheit = NSDecimalNumber(string: celciusString)
            .decimalNumberByMultiplyingBy(9)
            .decimalNumberByDividingBy(5)
            .decimalNumberByAdding(32)
        self.init(temperatureInFahrenheit : fahrenheit)
    }
```

NB: There are some edge cases where this doesn't work with UIKit/Foundation classes.

**Comment by sahara108** [comment]
Yes, I tried mark the method as `dynamic` but it still crashes.

**Comment by jasperblues** [comment]
Not good. Since its a convenience initializer that's chaining off the main one can you also try marking that dynamic? 

```Swift
    public dynamic init(temperatureInFahrenheit : NSDecimalNumber) {
        _temperatureInFahrenheit = temperatureInFahrenheit;
        
        _shortFormatter = NSNumberFormatter()
        _shortFormatter.minimumFractionDigits = 0;
        _shortFormatter.maximumFractionDigits = 0;
        
        _longFormatter = NSNumberFormatter()
        _longFormatter.minimumFractionDigits = 0
        _longFormatter.maximumFractionDigits = 1
        
    }
```

**Comment by sahara108** [comment]
It still doesn't work.

**Comment by jasperblues** [comment]
Will investigate ASAP. Possible to show code on a fork? 

Meantime, if this is an urgent problem, suggest using property injection.

**Comment by sahara108** [comment]
I have uploaded the code. It isn't an urgent problem. I am investigating Typhoon and may use it in the future.

**Comment by jasperblues** [comment]
Objective-C is very stable - there are hundreds of Typhoon apps deployed, and we use it daily on our own projects. Typhoon with Swift remains somewhat experimental. Swift, having no native reflection, and aggressively optimizing towards static and vtable dispatch, means there are some quirks. 

We are waiting to see if Apple will improve interoperability with Objective-C or instead provide native solutions to reflection and runtime method interception (AOP).

**Comment by sahara108** [comment]
Thanks for the information. Since, Swift isn't really stable right now, I intend use both Objc and Swift in my next project, ObjC for the business part and Swift for UI part. Could you please give me some advise about my approach? Is it a good way? Thanks very much.

**Comment by jasperblues** [comment]
> Could you please give me some advise about my approach? Is it a good way?

I couldn't really say, since it depends on the project, team skills, etc. I'm sure for this specific case you'd know better than me. 

As for using Typhoon in a Swift project. It will be more complicated than with Typhoon with Objective-C. We don't currently use Typhoon/Swift ourselves on our own projects yet. Based on the bug reports, for the most part it works, however it is sometimes necessary to make code changes to work around issues. (eg use property injection instead of initializer injection, as suggested above). Its up to you if you think this is acceptable, but we've marked the issue as 'show-stopper'. 

**DI Options with Swift**

* Use manual dependency injection. Keep pulling dependencies up, until you have a top level 'assembly' responsible for instantiating objects. 
* Use Typhoon. Be aware that there are some quirks, since it uses the Objective-C runtime with Swift. In theory this should be fine, but there appears to be some edge cases where Swift does over-aggressive optimization and workarounds are required. 
*  Use a Pure Swift DI container like <a href="https://github.com/jkolb/FieryCrucible">Fiery Crucible</a>. Because Swift has no native reflection, the feature set that such a container could provide will be more minimal, however being native there won't be any quirks or edge cases to contend with.

**Comment by sahara108** [comment]
The project uses some C++ library so it is required to use ObjC. I prefer to use dependency injection in my next project, so that I will use objC and keep an eye on this framework. Until it is fully compatible with Swift, I will switch the UI code to using Swift. Anyway, thank you for help.

**Comment by jasperblues** [comment]
You're welcome. Thanks for choosing Typhoon :)
