### ISSUE TITLE
Question: Can I use a class convenience method in an assembly initializer?

### ISSUE THREAD

**Issue by iosdev-republicofapps** [appsquickly/Typhoon#312]
Suppose I have my Knight class as follows:
````
@class Quest;

@interface Knight : NSObject
- (id)initWithQuest:(Quest *)quest;
- (void)importantPostInitializationSetup;
@end
````

Let's say that importantPostInitializationSetup can't be done inside the initializer for some reason.  Now, I know I could code my assembly like the following:
````
- (Knight *)basicKnight
{
    return [TyphoonDefinition withClass:[Knight class] 
        configuration:^(TyphoonDefinition* definition) {

        [definition useInitializer:@selector(initWithQuest:) 
            parameters:^(TyphoonMethod *initializer) {

            [initializer injectParameterWith:[self defaultQuest]];

        }];

        [definition injectMethod:@selector(importantPostInitializationSetup) 
            parameters:^(TyphoonMethod *method) {
        }];
    }];
}
````

But this exposes the importantPostInitializationSetup method.  I'd rather use a class convenience method like the following:
````
@class Quest;

@interface Knight : NSObject
+ (instancetype)knightWithQuest:(Quest *)quest;
@end

@implementation Knight
- (instancetype)initWithQuest:(Quest *)quest { // as before }
- (void)importantPostInitializationSetup { // as before }

+ (instancetype)knightWithQuest:(Quest *)quest
{
    Knight *knight = [[Knight alloc] initWithQuest:quest];
    [knight importantPostInitializationSetup];
    return knight;
}
@end
````

Is it possible to use + knightWithQuest inside a Typhoon definition?

Thanks!

**Comment by jasperblues** [comment]
Yes! No problem at all. All of the Objective-C idioms work. An initializer can be a class/factory method (also works with class clusters) or a regular initializer. 

*Swift Gotcha!* In Swift when you create a factory method that points to an init, sometimes Swift will just directly map to the init, so the extra code in the factory/class initializer won't run!  :-1: 

Please in future post general questions to StackOverflow as it helps other users, and shares the support load, so that we can keep improving Typhoon.
