### ISSUE TITLE
Building the Typhoon.framework Library

### ISSUE THREAD

**Issue by zenkimoto** [appsquickly/Typhoon#316]
Hello!  Nice project!  I just cloned Typhoon Framework and tried to build the framework but it is failing when I'm trying to build the Cocoa framework library.  The error indicates that UIDevice is an undeclared identifier (the other error is in reference to UIUserInterfaceIdiomPad being unidentified), but I've checked to see if the framework target has UIKit as a linked framework and it does.  I've even checked the Build Phases tab and I don't see anything wrong.  How do I just clone the project and build the Cocoa Framework library?

**Comment by jasperblues** [comment]
The framework target was contributed by @mowens . . perhaps he's available to take a look? Otherwise we'll investigate ASAP. 

Meanwhile, we recommend using Typhoon with <a href="http://cocoapods.org/?q=Typhoon">CocoaPods</a>. By default CocoaPods creates a static library, but if you specifically want a framework, it can support that now too.

**Comment by zenkimoto** [comment]
Thanks @jasperblues!  I do have the beta version of CocoaPods (0.36 beta 2) and it still creates a static library for Typhoon for some reason.  I didn't look too heavily into it.  I decided to follow your documentation on creating a git submodule for swift to build a dynamic framework.  It didn't build there, so I just cloned the project and tried to build it.  

I was planning on using Swift on a project and seeing if I could just use frameworks instead of using a bridging header, but I can always go the recommended approach if the framework route is not ready.  Thanks for your help.

**Comment by jasperblues** [comment]
@zenkimoto I believe that documentation should be updated as @mowens  is now recommending CocoaPods. Here's an example: 

```ruby
# platform *must* be atleast 8.0
platform :ios, '8.0'

# flag makes all dependencies build as frameworks
use_frameworks!

# framework dependencies
pod 'Typhoon', '2.3.3'
```

**Comment by jasperblues** [comment]
Does the above work for you?

**Comment by jasperblues** [comment]
#281

**Comment by mowens** [comment]
@zenkimoto Yes @jasperblues  is correct in that it would be ideal to leverage CocoaPods instead of the dynamic framework target, however the target should still build (last I checked from master). Note that you have to use the `use_frameworks!` in order to force the project to build as a dynamic framework (CocoaPods will automatically build pods as dynamic frameworks only if they contain swift code, thus you want to force pods to build as frameworks).

I will look into the framework target sometime tonight as that should still be a valid way to include the project.

**Comment by jasperblues** [comment]
Thanks @mowens , once @zenkimoto  confirms Podfile example works, I'll update docs to recommend that as the first course of action, while the manual build remains an option.

**Comment by zenkimoto** [comment]
Hi @jasperblues @mowens 

Thanks guys!!!  I used Cocoapods with the use_frameworks! specification and it works.  I guess I should have tried that.  (But if I did, I probably wouldn't have reported this issue :-D)  I do prefer Cocoapods over manually building.  Thanks for your help, it's working great now.

As far as why the framework isn't building, I'm not sure.  Perhaps it's my setup?
