### ISSUE TITLE
support auto-injection for swift

### ISSUE THREAD

**Issue by talarari** [appsquickly/Typhoon#335]
following this question on stack overflow:
http://stackoverflow.com/questions/29467353/auto-injection-with-typhoon-swift/29467669#29467669
 
currently there's no way to auto wire injections for swift, this generates a big overhead registering everything explicitly in the typhoonAssembly.
would be great to have a name convention for injected properties/parameters etc and only having to register the class. (if that can be saved too somehow would be great).
something like haveing a name prefix for properties that are injected

**Comment by jasperblues** [comment]
A name prefix seems a little invasive to me, but I can't think of any other ways to support 'auto injection for Swift. 

Whatever is implemented, suggest using a `TyphoonDefinitionPostProcessor` to make it optional behavior of the DI container, with a shorthand to turn the feature on/off.

**Comment by alexgarbarev** [comment]
:+1: Good idea!

**Comment by alexgarbarev** [comment]
... But this would works only for those properties which has objective-c representation. Since only objective-c runtime has ability to browse properties

**Comment by jasperblues** [comment]
Pedantic: Technically you can ***browse*** properties in Swift, but there's no facility for reflectively setting them, or for dynamic method invocation (initializer & method injection) or method interception (instrumenting assemblies). 

```swift
class Fruit {
    var name="Apple"
}

reflect(Fruit()).count         // 1
reflect(Fruit())[0].0          // "name"
reflect(Fruit())[0].1.summary  // "Apple"
```

**Comment by Imran99** [comment]
Hi Guys,
I am very interested in this too. Would it be possible to have a convention that injected by type based on if the type has been registered in the container? Is typhoon able to resolve dependancies like this in multiple passes? so that you can say register an implementation for IMyComponent and then have this auto injected in to your view controller when typhoon comes across a property of type IMyComponent?

**Comment by jasperblues** [comment]
@Imran99  Yes, Typhoon first loads all definitions (recipes) into `TyphoonComponentFactory` and then instantiates based on these rules. By-type injection is only available for properties, as the Objective-C runtime doesn't provide this information for initializer and method arguments. 

For Objective-C there's also auto-registration into the container. So that for an object that declares auto-injection macros you don't have to create a definition in an assembly. 

For Swift I suggest something like using functional sugar to arrays: 

```swift
definition.injectAllProperties().excluding([a, b])
```

**Comment by Imran99** [comment]
oh so auto wiring by type in swift for properties at least is already implemented?

**Comment by jasperblues** [comment]
@Imran99 Yes you can already write: 

```swift
definition.injectProperty("musicCatalog")
``` 

. . and it will match the declared protocol or class of the property. But folks are asking if there's a neater/faster way to do it in Swift. Unfortunately, the [[Auto-injection-(Objective-C)]] won't work for Swift.

**Comment by Imran99** [comment]
ok now I understand, thats exactly what I'm looking for too. Your "definition.injectAllProperties().excluding([a, b])" suggestions looks quite clean to me too and would nicely avoid magic strings.

**Comment by jasperblues** [comment]
@Imran99 

Yes, at least until you needed to exclude a property. Its a shame selector is not a first-class type.

**Comment by Imran99** [comment]
You may only want to exclude a property when its something like an 'int' i suppose? Even then you probably wouldn't be able to get around injecting by magic string since you may have multiple ints e.g. some sort of config value injection. In that case you might just define an IconfigParam... and inject that instead.

**Comment by jasperblues** [comment]
@Imran99 

Yes, or view controllers is another example. Its common to define an injected view for a complex controller/view but perhaps not all controllers will have an injected view. 

Another thing to consider is: 

* Inject only if there's a matching property in the container. 
* *Require* the property to be injected, otherwise fail early

**Comment by Imran99** [comment]
Just thinking out loud, not sure if this would be possible and excuse the possible swift syntax errors ;) How about something like:

```
definition.injectAllProperties().excluding( {exclusions in 
    exclusions.injectPropertyExplicitly("someView", MyView.self)
    exclusions.injectPropertyExplicitly("integerConfig", 5)
})
```

**Comment by fatuhoku** [comment]
+1 really wishing that Typhoon could be a bit smarter to save lots of typing.

**Comment by Alphasite** [comment]
Would something akin to what Realm does work? It uses the dynamic modifier to indicate which properties can be automatically injected. It does of course have some limitations on types, but i believe those are a database limitation, rather than a limitation for the underlying system.

**Comment by jasperblues** [comment]
At @Alphasite Can you show a code example? Are you referring to Realm for Objective-C or Swift?

**Comment by Alphasite** [comment]
Sorry, you have probably seen how realm does it, but it does just do something like (For [Swift 2.0](https://github.com/realm/realm-cocoa/blob/master/RealmSwift-swift2.0/Object.swift)):

    class Apple: Object {           // Realm.Object is an Objective-C runtime class.
        dynamic var seeds = 0       // Default value
    }

Which is then instrumented automatically by the Realm Swift/Objective-C runtime. I hope that was relevant to this discussion? I haven't checked this, but I would assume automatic registration is due to inheriting from Object.

**Comment by jasperblues** [comment]
@Alphasite Hmmm, that idea does have some merits. To confirm you're thinking of a base class like `Injectable.Object`. 

And use it like: 

```swift 
class Apple : Anything {
    dynamic var seeds : Injectable  //Any subclass of Injectable is auto-injected
}
```

Right?

**Comment by Alphasite** [comment]
Not quite, but It may work as well. I don't know the ins and outs well enough to comment.

**Comment by alexgarbarev** [comment]
When I'm thinking about AutoInjection for swift, I'm thinking about some global variable for Typhoon DI container singleton, then do something like

```swift
class Apple {
    var dependency = typhoon["definitionKey"] : MyDependency1
    var dependency2 = typhoon[MyDependency1.self]
}
```
not sure if this good idea, since uses singleton (i.e. one factory for whole app)

**Comment by jasperblues** [comment]
It also directly couples the class to Typhoon, but so does sub-classing a special class to designate 'injectable'. . in both cases these are undesirable traits, so they are not my first choice.

**Comment by alexgarbarev** [comment]
@jasperblues I think any auto-injection approach is couples class with Typhoon. Isn't it?

**Comment by jasperblues** [comment]
yeah, true. . . but I'm happy with the ObjC macros - they are nice.

**Comment by Alphasite** [comment]
Out of interest, what level of auto injection are you looking for exactly? 

I'm curious whether or not there is any value in having an injectable protocol? They can be implemented as an extension, so the coupling shouldn't be as much of an issue, should it?

e.g.

     protocol injectable {
          optional var InjectFields: [String] { get }
          optional var DoNotInjectFields: [String] { get }
          
          optional func factory() -> self
          // or if you want different initialisations of the same object.
          subscript { 
               get(instance_type: string) {
                    ..
               }
          }
     }

    class Apple: NSObject {
        dynamic var dependancy1: Realm!
    }

     // This could be in a separate file, e.g. the Assembly file?
     extension Apple: injectable {
         // Indicates that it should be injected
         // Can explicitly list injectable fields (inclusion/exclusion)
         var InjectFields: [String] { return [dependancy1] } // This could have a d default implementation which reflects on the objects fields.
         var DoNotInjectFields: [String] { return [dependancy2] }

         // You could even have an optional factory method? 
         // Which calls the initialiser directly and removes any boilerplate there.
         
     }

As i said above, I really dont know enough about this to know if its possible, but could that be a workable solution, which address a couple of your concerns?

**Comment by jasperblues** [comment]
@Alphasite that looks pretty good for a solution that uses the ObjC runtime. Another thing we've been talking about is a version of Typhoon that works with 'pure' Swift.

**Comment by Alphasite** [comment]
Ah. So this is for pure swift objects?

**Comment by jasperblues** [comment]
"Pure" Swift only uses a small subset of the Objective-C run-time. Challenges: 

- There is no reflection beyond readonly reflection for tool support. 
- Method invocation is inline, static or vtable so there's no method interception/instrumentation

You can still do a DI container. Here's a good example of one approach: https://github.com/jkolb/FieryCrucible

**Comment by Alphasite** [comment]
Two comments then:

1. Is it yet possible to have generic subscripts, without generic classes in Swift 2?
2. You could rely on file level scope using __FILE__, although ideally something like __NAME__ (to indicate the closest scope identifier, e.g., main, function name, class name, etc.)

I don't know of a way to get __NAME__ but it may be worth filing a radar about it?

**Comment by jasperblues** [comment]
Closing this ticket in favor of writing a 'pure swift' injector that does not need reflection or ObjC runtime features . . the ObjC runtime could provide auto-injection, but depending on this already gives a list of constraints and quirks. Maybe not a good idea to keep adding to that list.
