### ISSUE TITLE
Storyboard integration doesn't work with Share Extensions

### ISSUE THREAD

**Issue by cakper** [appsquickly/Typhoon#352]
Hello,

I've tried to use Typhoon storyboard integration with the Share Extension that I'm working on at the moment and as extension doesn't have AppDelegate it doesn't seem to work properly. Probably that will be the case with all extensions supported by new iOS as they are not normal apps and have different lifecycle.

Manual injection as described on this page: https://github.com/appsquickly/Typhoon/wiki/Activating-Assemblies#instructing-typhoon-to-inject-a-pre-obtained-instance works as expected, but adds a bit of noise to the view controllers (works well as a workaround).

To give a bit more context what was already discussed here is the link to twitter: https://twitter.com/cakper/status/599245416442507264
And sample project created to demonstrate the problem: https://github.com/cakper/TestExtensionApp
https://github.com/cakper/TestExtensionApp/blob/master/Podfile.lock contains versions of the Typhoon and Cocoapods used

Thank you, Kacper :)

**Comment by alexgarbarev** [comment]
Sorry, haven't tried iOS extensions yet..

How UIStoryboard instance is created in the extension? Manually, with ``[UIStoryboard storyboardWithName:bundle:]```? Or it's created by iOS automatically?

if automatically, how iOS know storyboard name? Using value for special key in `Info.plist`?

**Comment by cakper** [comment]
Hello Alex,

Storyboard instance is created by extension automatically. It is using `NSExtension -> NSExtensionMainStoryboard` entry from extension `Info.plist` file.

**Comment by alexgarbarev** [comment]
Ok, I'll add support for that soon then

Отправлено с iPhone

**Comment by cakper** [comment]
Nice, Thanks ;)

**Comment by alexgarbarev** [comment]
Hey, @cakper. Can you test latest code with `:head` version of Typhoon?

**Comment by cakper** [comment]
Hello, @alexgarbarev - sure - I'll have a look in a sec

**Comment by cakper** [comment]
Hi @alexgarbarev 

So we had a look at it and it doesn't work as expected. After going though Typhoon code what we found is that in `swizzleSetDelegateMethodOnApplicationClass` is replaced with your implementation that calls `[self loadInitialFactory];` which is fine, but the problem is that `setDelegate` is never called (because app is not instantiated) and in result the initial factory is never loaded.

Trying to think about right place to inject with factory initialisation for extension - what do you think about swizzling `storyboardWithName` in `UIStoryboard` and calling load there?

**Comment by alexgarbarev** [comment]
Hi @cakper 

Injection for storyboard doesn't work?

Now, about the code. I appreciate your attention to code and good suggestions.
There is two files you would like to check.

**TyphoonStartup.m**
There is loading initial factory and trying to inject into `AppDelegate` if possible. 
Loading initial factory done on `+(void)load` method, using `TyphoonInitialAssemblies` key in `Info.plist` (or using `[AppDelegate initialFactory]` - not this case)

Initial factory loaded at very start of application startup and released after application did finish launching ( at *UIApplicationDidFinishLaunchingNotification* notification on iOS)

**TyphoonInitialStoryboardResolver.m**
This class is designed to provide storyboard integration at application startup. As you suggested, it uses swizzling of `storyboardWithName` method. Inside this method, I'm checking for *initial factory* which must be provided by *TyphoonStartup* class - if initial factory exists `TyphoonStoryboard` will be created instead of `UIStoryboard` (as class cluster).

----

Now, back to the problem.
I guess next reasons:
1) Initial factory was not created (missing `TyphoonInitialAssemblies` in the plist)
2) Initial factory was created, but released before UIStoryboard creation

If you have spare time, you can try to debug using information from above and make pull request with fix, I haven't so much time to play with iOS extensions now. (Will fix later)

**Comment by cakper** [comment]
Hello

> There is loading initial factory and trying to inject into AppDelegate if possible.
I think problem here is that `swizzleSetDelegateMethodOnApplicationClass` doesn't work at all because there is no AppDelegate in the Share extension.

I did try to run `loadInitialFactory` later manually and then it works fine (so it loads Assemblies from the plist file without any problems and is injecting everything fine. So the I still think our ultimate problem here is that there is not AppDelegate for the extension target. Did you try to play with the sample project I've provided?

**Comment by jasperblues** [comment]
@cakper We'll get to this ASAP. Meanwhile if you want to tackle this yourself, it sounds like simply a matter of: 

* Find the correct hook point
* Copy the same approach that TyphoonStartup uses for AppDelegate

We'll happily accept a pull request for this.

**Comment by alexgarbarev** [comment]
I'll fix that issue. I hope I'll have time at today's evening

**Comment by alexgarbarev** [comment]
@cakper You was totally right. The reason was: TyphoonStartup loads `initialFactory` only when Application Delegate class exists.
Now fixed and released as 3.1.8. Thanks for catching that!
