### ISSUE TITLE
Assembly graph with loop can only be activate from Root

### ISSUE THREAD

**Issue by itsthejb** [appsquickly/Typhoon#362]
Hi guys,

Have an issue here where I have an assembly graph that contains a loop (not ideal, but that's how it is right now). Something like:

App Assembly -> View Controller Assembly -> Router Assembly -> App Assembly

Ideally I'd like to break this loop, but it seems to work fine when the root assembly (App Assembly) is activated and use within the app. However, if I'd like to active from a point within the graph (say, View Controller Assembly), then I get an infinite loop in `-[TyphoonAssembly collectCollaboratingAssembliesBackTo:]`.

So my question is, is this expected behaviour? I could solve this my deactivating one of the collaborating assemblies when I'm testing, but it's not obvious how to do this.

Any help appreciated!

**Comment by jasperblues** [comment]
That sounds like a bug. The intended effect in the above case would be: 

* You'd end up with exactly the same underlying TyphoonComponentFactory backing your assemblies. 
* If you activate from `ViewControllerAssembly` you'd be able to access built instances from `AppAssembly` with `[ViewControllerAssembly.routerAssembly.appAssembly someComponent]`

**On startup:**

* Typhoon instruments you assemblies to assign a unique key (based on method name) for each definition. 
* For each collaborating assembly proxy is used so that the concrete realization can be provided on activation. 

**On Activation:**

* Typhoon will find the set of assemblies to use by looking at the concrete types in any collaborating assemblies, and any that you've specified explicitly. Explicit ones will override implicit ones. 
* A `TyphoonComponentFactory` is built where every definition from each assembly is registered. 
* In active mode your assemblies are now a proxy to `TyphoonComponentFactory`. When you send a message to them it is forwareded to the underlying factory's `componentForKey` method.

**Comment by jasperblues** [comment]
**Workaround:**

We'll fix ASAP. Meanwhile in tests just activate the top assembly and tests infra-level components with `[appAssembly.vcAssembly.routerAssembly someComponent]`

**Comment by itsthejb** [comment]
Hi,

Yep, no problem, that's fine enough. Also, if it's interesting at all, I was using an OCMock object as a runtime argument to one of these definitions in tests and got:

```
*** NSForwarding: warning: object 0x7fabc3902ec0 of class '__NSMessageBuilder' does not implement doesNotRecognizeSelector: -- abort
```

This is probably caused by doing something with the `OCMock` proxy. Perhaps this is some support that could also be added? Can use a "real" object in the tests for now.

**Comment by jasperblues** [comment]
Ah, thanks for reporting about OCMock. I'll raise that as a separate issue bug - we'll try to fix it. 

Yes, one of the nice things about dependency injection is it simplifies integration testing as well as unit testing. Integration tests give plenty of 'bang for buck', but two drawbacks: 

*  It can be difficult to set up the system into the required state for a particular test scenario. 
* Testing with real components can have side-effects that are difficult to rollback. 

We can work around this by using mostly real components (an assembly) but just patch one one or two. Typhoon provides: 

* Ability to back assemblies with a protocol, and provide the concrete realizations on startup. 
* Ability to provide a sub-class assembly to act in place. 
* TyphoonPatcher

. . but it didn't occur to me about using mocks in runtime args.

**Comment by itsthejb** [comment]
Sure. I'm not actually using the mock to do anything clever here, just wanted a benign pointer to use, so no problem to swap it to a non-proxy in this case. I can possibly imagine using actual mocks being useful in the future, though, so that would be handy support to add.

Thanks!

**Comment by itsthejb** [comment]
Hey there - I've just been reminded today that this one is still an issue for us (with 3.2.1). Hope there's something in the works for the future.
