### ISSUE TITLE
Does typhoon have any known issues with ios9

### ISSUE THREAD

**Issue by khappucino-nordstrom** [appsquickly/Typhoon#395]
We are researching readiness for ios 9 and we wanted to see if there were any known issues with the current beta of ios 9.

Thanks

**Comment by jasperblues** [comment]
Hello @khappucino-nordstrom, 

We are not anticipating any problems with iOS9. Most of Typhoon leverages the Objective-C runtime, which is mature and very static. (No changes between versions). These features are also well addressed by our test suite, which can be run on or off device. 

The one risky feature is the plist-style of integration, which hooks into AppDelegate during start-up. This is so that: 

* UIStoryboards behave as Typhoon storyboards - work just like regular storyboards with the added benefit of dependency injection. 
* Typhoon hooks in early enough that UIStateRestoration works as expected. 

If a future version presents issues here, we're confident that they could be easily addressed with minor tweaks, but in the worst case users could simply fall back to the 'activation' style of bootstrapping.

**Comment by khappucino-nordstrom** [comment]
Thanks for the quick response @jasperblues

**Comment by jasperblues** [comment]
@khappucino-nordstrom You're welcome. 

> leverages the Objective-C runtime, which is mature and very static.

Oops, it looks like this was a poor choice of words. By 'static' I meant that the API and features serve as the foundation for what has been built on top over many years, and are therefore very unlikely to change in breaking ways. The run-time itself is very dynamic. I'm sure you caught my meaning ;)
